spring:
  profiles: dev   # 开发环境
  application:
    name: cloud-provider-dev
---

spring:
  profiles: test   #测试环境
  application:
    name: cloud-provider-test
---

spring:
  profiles:  pro   #生产环境
  application:
    name: cloud-provider-pro
  