server:
  port: 8888
spring:
  application:
    name: config-client-8888-sss
  cloud:
    bus:
      trace:
        enabled: true
    config:
      fail-fast: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh